import json
import pandas as pd
from pathlib import Path


def save_json(data: dict, path: str):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False, default=str)


def load_json(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def validate_forecast_input(df: pd.DataFrame) -> bool:
    required = ["ds", "Ingresos"]
    return all(c in df.columns for c in required)


def fiscal_quarter(month: int) -> str:
    if month <= 3:
        return "Q1"
    elif month <= 6:
        return "Q2"
    elif month <= 9:
        return "Q3"
    return "Q4"


def generate_executive_summary(metrics: dict, insights: list, anomalies: list) -> str:
    lines = ["# Executive Summary — Financial AI Forecast\n"]
    lines.append(f"**Generated:** {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}\n")

    if metrics:
        lines.append("## Model Performance\n")
        for k, v in metrics.items():
            lines.append(f"- **{k}**: {v}")

    if insights:
        lines.append("\n## Forecast Insights\n")
        for ins in insights:
            lines.append(f"- {ins}")

    if anomalies:
        lines.append("\n## Anomalies Detected\n")
        for a in anomalies[:5]:
            lines.append(f"- {a}")

    lines.append("\n---\n*Report generated by Keedio Financial AI Forecasting System*")
    return "\n".join(lines)


def export_for_powerbi(df: pd.DataFrame, path: str = "data/processed/for_powerbi.csv"):
    export = df[
        ["ds", "Proyecto", "Cliente", "Servicio", "Ingresos", "HorasFacturadas",
         "CosteEquipo", "MargenBruto", "margen_pct", "Seniority", "Satisfaccion",
         "year", "month", "quarter"]
    ].copy()
    export["ds"] = export["ds"].dt.strftime("%Y-%m-%d")
    export.to_csv(path, index=False, encoding="utf-8-sig")
    return path
